[Seat:*]
# Force LightDM to assume the login user is root
autologin-user=root
autologin-user-timeout=0

# Hide user list and username field
greeter-hide-users=true
greeter-show-manual-login=false

# Require password even for autologin-user
allow-password-autologin=true

# No guest, no other users
allow-guest=false

