#!/bin/bash

set -e

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer netinst \
    --debian-installer-gui true \
    --bootloader syslinux \
    --apt-source-archives false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-flavours amd64 \
    --system normal \
    --memtest none \
    --apt-recommends false
