#!/bin/sh
set -e

# Only set default options.

LB_MODE="debian"
LB_DISTRIBUTION="trixie"
LB_ARCHITECTURES="amd64"
LB_BINARY_IMAGES="iso-hybrid"
LB_DEBIAN_INSTALLER="live"
LB_DEBIAN_INSTALLER_GUI="false"
LB_BOOTLOADER="syslinux"
LB_APT_SOURCE_ARCHIVES="false"
LB_ARCHIVE_AREAS="main contrib non-free non-free-firmware"
LB_LINUX_FLAVOURS="amd64"
LB_SYSTEM="normal"
LB_MEMTEST="none"
